### ISSUE TITLE
Editable .cpmproject file?

### ISSUE THREAD

**Issue by RepeatGitHub** [Ohmanit/Slugcat-MC-Skins#1]
Hello Ohmanit! I was wondering, could you upload your .cpmproject file for the slugcat model too? I was thinking of making a custom slugcat based on your model, but from what I've heard it's much harder to edit a .cpmmodel's texture than a .cpmproject's.

Thanks!
\- RepeatGitHub

**Comment by Ohmanit** [comment]
Hey RepeatGitHub! Someone asked me a similar question a few days ago and I still haven't decided if I should post the .cpmproject file or not. I fear my model being republished without my credit, but I still want to let players edit their skin. I did see a skin compatible option when I exported the models, so I'll test and see if this option lets the player customize the skin without changing or having the ability to clone the model. 

I'll update if I find a solution!

**Comment by RepeatGitHub** [comment]
Alright, thanks for coming back to me about this! Good luck with the solution!

**Comment by CliffracerX** [comment]
IIRC Skin Compatible is about fitting models into the extra data within a Minecraft skin, rather than making it editable.  I would like to second the ask for a cpmproject- I wanna tinker with making some modcats & OCs on this base, it looks really good and so far most of the other slugcat models are on Figura.

**Comment by Ohmanit** [comment]
I see, since even more people asked me for the file on other sites I'll think through it and I might just release the cpmproject file with a request not to republish or claim it.
